### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-2-Papoyan** [UMSF-K13-2-Papoyan/K13-2-Papoyan-MainProject#1]
![image](https://cloud.githubusercontent.com/assets/19632897/15635339/10380f9c-25e5-11e6-977a-cd381f5b46be.png)
После изменений в файле
![image](https://cloud.githubusercontent.com/assets/19632897/15635349/4a08be1a-25e5-11e6-9ed6-1877ac13c18b.png)
![image](https://cloud.githubusercontent.com/assets/19632897/15635354/5215839a-25e5-11e6-8ef3-e67c1960b629.png)
После нажатия на кнопку commit
![image](https://cloud.githubusercontent.com/assets/19632897/15635365/94605d4c-25e5-11e6-8fab-939d8dd8f016.png)
![image](https://cloud.githubusercontent.com/assets/19632897/15635377/eec1efc6-25e5-11e6-805a-2fa754ea8174.png)
После нажатия на Push
![image](https://cloud.githubusercontent.com/assets/19632897/15635550/bb44cb06-25e9-11e6-8e5f-31831c0adff1.png)

**Comment by Smoktii** [comment]
Ок
